---
- name: Creating and updating users list
  user:
    name: "{{item.name}}"
    password: "{{item.password | password_hash('sha512', 'A512') }}"
    update_password: "{{item.update_password | default(always) }}"
    uid: "{{item.uid}}"
    home: "{{item.home}}"
    create_home: "{{item.create_home | bool }}"
    move_home: yes
    state: "{{item.state}}"
  with_items: "{{ users_list }}"
  when: users_list | length > 0
  tags: 
    - high_severity
    - medium_severity
    - low_severity

